### ISSUE TITLE
Issues with Firewall

### ISSUE THREAD

**Issue by inboxcda** [j4ym0/pia-qbittorrent-docker#14]
Hello, thanks for making this cool mix of a docker container with qbit.

When starting my container it constantly fails to connect as you will see in the logs below. I have followed all of your instructions for ports but it still hangs on trying to determine the Swiss Pia addresses. If I disable my entire firewall, it works flawlessly. If I enable it, even though I followed all of your port suggestions on the read me page, it fails on the next restart.. I am unsure where to go from here to determine the issue.  I just want a clean startup each time without having to disable my whole firewall each time I have to restart my containers. While turning off my firewall gets it running, it seems reenabling wouldn't resolve the problem anyway but when trying to start a torrent, it immediately errors out. Unsure why but I think it has something to do with the ports soon my actual router and not my Asustor NAS firewall. If disabling my firewall works to the point I get an assigned PF PORT and a valid password for signing into user console, it would seem my home router isn't the problem and that it is my NAS firewall that's the issue.

I also enabled all ports in this PIA article here. At least alll on the PIA section and the 1198 on the openvpn section as instructed by your readme.
<img width="777" alt="image" src="https://github.com/user-attachments/assets/a0f78a5f-6a5c-46c9-8ff0-37f2278c5ba6">
<img width="728" alt="image" src="https://github.com/user-attachments/assets/dc6d3704-4aa0-4fa4-b790-6c3785df10d5">
<img width="725" alt="image" src="https://github.com/user-attachments/assets/e6d9bb62-fa41-4cc6-9e7f-e520d1503ba4">

I would appreciate any help or guidance you could offer.

 Unable to connect to swiss.privacy.network+ =========================================
 ============== qBittorrent ==============
 =================== + ===================
 ============= PIA CONTAINER =============
 =========================================
 OS: Alpine Linux v3.16
 =========================================
 OpenVPN version: 2.5.6
 Iptables version: v1.8.8
 qBittorrent version: v4.6.6
 =========================================
System parameters:
 * userID: 10
 * groupID: 1
 * timezone: UTC +0000
OpenVPN parameters:
 * Region: switzerland
Local network parameters:
 * Web UI port: 8888
 * Adding PIA DNS Servers
 * * Adding 84.200.**.** to resolv.conf
 * * Adding 84.200.**.** to resolv.conf
[INFO] /auth.conf already exists
[INFO] Clearing environment variables USER and PASSWORD...DONE
[WARNING] TUN device is not available, creating it...DONE
[INFO] Reading OpenVPN configuration...
 * Port: 1198
 * Domain: swiss.privacy.network
[INFO] Detecting IP addresses corresponding to swiss.privacy.network...
 Unable to connect to swiss.privacy.network

**Comment by j4ym0** [comment]
Looking at the log it is not able to connect to the DNS servers to resolve "swiss.privacy.network"

The container no longer uses Cloudflare DNS server 1.1.1.1 but uses DNS.watch in case of domain filtering. I will update the readme.

There should be no need to change/open any ports on a standard router. If you have a more sophisticated firewall that filters outbound and inbound connections to devices, this is were the ports should be opened to allow traffic to the container.

On your firewall remove the rules for 1.1.1.1.
Then add 84.200.69.80 UDP port 53 and 84.200.70.40 UDP port 53.
Then restart the container and it should connect

**Comment by inboxcda** [comment]
That’s good to know! Thank you! I’ll try that and update this thread after
testing.

**Comment by inboxcda** [comment]
Okay I removed the rules for 1.1.1.1. and adjusted the ports for those ip addresses.  Here is what I have configured in my firewall now but I still get the same issue. Am I missing a piece?
<img width="1124" alt="image" src="https://github.com/user-attachments/assets/a9ed5f23-cd65-4b62-a10d-ae2d0ddba0fc">
<img width="583" alt="image" src="https://github.com/user-attachments/assets/353752ab-a5d5-4c9b-b8a8-d5c599712ac4">

**Comment by inboxcda** [comment]
An interesting development.  Using Lil snitch to examine the network traffic on my local macOS docker build, I shut off connections one by one till I got the specific problem I am seeing on my NAS. You will see in the photo below, I disabled the DNS IPs on my Mac so they couldn't get in or out. That causing the same error upon restarting the docker container. The strange thing is that my NAS has those IPs and ports open.


<img width="641" alt="image" src="https://github.com/user-attachments/assets/2a0d776a-d1c3-437a-94ae-04734692efed">
<img width="1516" alt="image" src="https://github.com/user-attachments/assets/99de969c-859b-4f3d-b5a6-5b2ffee441ee">
<img width="614" alt="image" src="https://github.com/user-attachments/assets/17ce2af8-7e66-45e9-aa4a-ef0595a22841">

**Comment by j4ym0** [comment]
looking at the rules on the NAS, they look like they should work. Looking at the ADM demo the firewall seems to be for inbound connections.

Can any other container connect to the internet?
basic image `docker run -it --rm alpine ping swiss.privacy.network` or `docker run -it --rm alpine ping 84.200.69.80:53`

**Comment by inboxcda** [comment]
Interesting. As I’ve setup services it’s always seemed that it affects
inbound and outbound. I do have a few apps that I have been able to connect
to the outer world once configured. But ADMs firewall interface is trash.
So I’m looking into putting a firewalla in front of it. I’ll do some more
testing at some point. The issue is definitely on my side so you’re welcome
to close this issue if you feel inclined. I’ll post an update one of these
days.
