### ISSUE TITLE
Upload statistics and tags reset on container restart

### ISSUE THREAD

**Issue by jdtaormi** [j4ym0/pia-qbittorrent-docker#15]
Hello, thank you for this docker container. The one issue I have with it is that, on container restart, all upload statistics and tagged torrents get reset. It also rechecks all torrents on restart. Curious if this is intended or an open issue?

Here is my docker-compose for reference:

services:
    pia-qbittorrent:
        init: true
        container_name: pia-qbittorrent
        cap_add:
            - NET_ADMIN
        volumes:
            - /home/pi/torrent:/downloads
            - /home/pi/docker/qbittorrent/config:/config
        ports:
            - 8888:8888
        environment:
            - REGION=US_East
            - USER=<pia_username>
            - PASSWORD=<pia_password>
            - PUID=1000
            - PGID=1000
        image: j4ym0/pia-qbittorrent

Thanks!

**Comment by j4ym0** [comment]
This is not usual. In my setup the torrents will resume at the point that qBittorrent is shut down, unless the docker is stopped from command line. The recheck is usually triggered when there is a inconsistency.

Please check your config folder `/home/pi/docker/qbittorrent/config/config/qBittorrent/data/BT_backup` this dir will contain your .torrent and .fastresume files. check you have these files and the permissions of the folder is correct.
To replace the permissions of the config folder `sudo chown 1000:1000 -R /home/pi/docker/qbittorrent/config`

You could adjust your 'Save resume data interval'. Go to Tools at the top click Options and click the Advanced tab. The Save resume data interval: is usually set to 60 mins as default, you could change this to 1 min or 5 min. After saving click File and Exit qBittorrent, this will close qbittorrent and save the fastresume and the settings. Once the container is restarted this will save the resume data more frequently

**Comment by jdtaormi** [comment]
Thank you for the info, I will try this.
