### ISSUE TITLE
Latest release undefined error when flushing iptables rules

### ISSUE THREAD

**Issue by owenvoke** [j4ym0/pia-qbittorrent-docker#16]
Since updating to yesterdays release, I am getting the following error when the `latest` Docker image tries to boot.

```log
[INFO] Setting firewall
* Block everything
* Deleting all iptables rules... iptables v1.8.10 (nf_tables): Could not fetch rule set generation id: Invalid argument
[ERROR] Undefined error, with status 4
```

I'm assuming this is maybe related to the Alpine 3.20 upgrade? 🤔 However, looking at [3.19](https://pkgs.alpinelinux.org/packages?name=iptables&branch=v3.19) and [3.20](https://pkgs.alpinelinux.org/packages?name=iptables&branch=v3.20), iptables is version `1.8.10-r3` for both. 🤷🏻

**Comment by jordilaforge** [comment]
Hi There I get exactly the same error. Is there already a fix?

**Comment by jordilaforge** [comment]
I run the latest j4ym0/pia-qbittorrent:latest on a synlogy nas. NET_ADMIN is already added.

**Comment by j4ym0** [comment]
@jordilaforge Doing some quick research, Synology DSM does not come with nft. 
If you are able to SSH into you Nas can you try running 'nft --version' to see if it is installed. If not try installing it apt-get update && apt-get install nftables

Nftables is the new backend for iptables firewall in 1.8.x. I suspect this could be the issue.

**Comment by jordilaforge** [comment]
could you provide the old version till I can have a look into that. On dockerhub I only see the lastest. Would be nice to have older verisons too. Thanks

**Comment by j4ym0** [comment]
@jordilaforge I will rebuild them when I get back later this afternoon. Have you tried the Ubuntu image or is it just the alpine/latest?

**Comment by jordilaforge** [comment]
Same error with ubuntu image....

**Comment by j4ym0** [comment]
@owenvoke here was a jump from Alpine 3.16 to Alpine 3.20 due to a dependent requirement that is not available in alpine 3.17+ this has now been worked round. Hens the jump. You would have to use SSH to get access to the underlying Synology OS to install nftables, it woud not be a package though the webUI.

@jordilaforge i am rebuilding the old alpine 3.16 container with should be pushed in a few hours. `j4ym0/pia-qbittorrent:alpine-3.16"`

So looks like it is the host that does not have the nftables package causing the issue, even though the container firewall rules are using iptables. I will do some testing and come back.

**Comment by owenvoke** [comment]
Thanks for looking into this.

I was looking for the `nftables` package via SSH (rather than in the web UI). But I'm happy with using the `alpine-3.16` image for now. I can confirm it works fine! Thanks. 👍🏻

**Comment by marc115uk** [comment]
same issue here, on synology. Am using the alpine-3.16 image to temporarily fix it. Doesn't look like you can install nftable via ssh

**Comment by j4ym0** [comment]
I have a fix that will be pushed into the latest feed when i have done some more testing. 

i have pushed a preview with the docker tag synology. Set LEGACY_IPTABLES to true in your environment variables, tested on my DSM Vbox and works here.

**Comment by owenvoke** [comment]
Testing the new tag with `LEGACY_IPTABLES=true` on my Synology NAS and it seems to be working perfectly! Thanks.

**Comment by j4ym0** [comment]
pushed to latest feed on docker
