### ISSUE TITLE
Love this project; trying to run other containers thru the VPN??? 👍 

### ISSUE THREAD

**Issue by Paulie420** [j4ym0/pia-qbittorrent-docker#18]
I've added several other containers to the docker-compose.yml of this project to add overseerr, Radarr, sonarr, etc. I thought it would be nice to route those containers thru the pia-qbittorrent container - but I'm quickly realizing that I don't know how. I thought I could add some lines to route traffic thru:

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    network_mode: "service:pia-qbittorrent"
    depends_on:					
      - pia-qbittorrent
 
 ... does anyone know the CORRECT way? I haven't dug into pia-qbittorrent yet but thought I'd make a newb post.

**Comment by j4ym0** [comment]
@Paulie420 The container was not designed to work that way. It was designed so no traffic would leave the container once connected to the VPN. This is to prevent leaking of ipdata to ISP or local network.

It may be possible using a [Hook Script](#Hooks), probably need to add a new network to the container and unblock traffic on the iptables to new network adapter.

**Comment by Paulie420** [comment]
I now see - I poked around in the container. Thanks for your reply - since I'm running a larger stack now I might just make the entire LXC run behind PIA, but at that point I wouldn't really need pia-qbittorrent. :P

Thanks for a great project it works very nicely.

**Comment by j4ym0** [comment]
Thanks for you comments

**Comment by Paulie420** [comment]
I simply created a PIA wireguard setup on the entire server and created a systemd service for wg0. It runs at boot and the ENTIRE server is behind PIA now... pia-qbittorrent gets yet ANOTHER IP, s thats nice...

Having some issues creating a good killswitch for the entire server, but thats nothing to do with pia-qbittorrent - I realize now that continuing to use pia-qbittorrent is STILL beneficial so that my stack is behind one PIA IP, and qbittorrent gets yet another... nice.

Thanks again - I love this project!! Now, just to get indexer invites!!! :P
