### ISSUE TITLE
Better image tagging

### ISSUE THREAD

**Issue by migol** [j4ym0/pia-qbittorrent-docker#19]
Due to qBittorrent 5.0.0 showing up I wanted to lock down my version to 4 or 4.6 branch, but in seems there are no version tags on the images, just latest and few other. Would it be possible to have images tagged with major.minor at least and keeping latest in the line alive?

**Comment by j4ym0** [comment]
@migol I did start with version tags but got too complex for me to keep up with when I started multiple architecture support.

I can look at doing them again. How far back are you wanting?

**Comment by migol** [comment]
Well, for now I don't really need much back other than maybe 4.6 branch to make me stay before 5.0.0 upgrade.

**Comment by j4ym0** [comment]
@migol 4.6.7 tag has been uploaded to docker hub. I should still have some old version in cache  I could push.

**Comment by migol** [comment]
@j4ym0 thanks mate. It's up to you really, good system I saw is to also tag 4.6.7 image with 4.6 and 4 tags, just in case they decide to make 4.6.8 someday.

**Comment by j4ym0** [comment]
requested tags now available
