### ISSUE TITLE
DNS/Firewall failure on startup

### ISSUE THREAD

**Issue by RangerLink667** [j4ym0/pia-qbittorrent-docker#20]
Hi, thank you for your efforts on this image.
I am not able to resolve the PIA domains on startup. Instead, the container restarts itself after error message:
> 2024-10-06 23:46:55 [INFO] Detecting IP addresses corresponding to nl-amsterdam.privacy.network...
2024-10-06 23:47:15  Unable to connect to nl-amsterdam.privacy.network2024-10-06T20:47:16.916170602Z  =========================================

This issue occurs with even the provided "basic launch" command, with only the PIA username and password being provided, and occurs on every PIA server tested. I was able to ping out from the container to 84.200.69.80 and 84.200.70.40, but a manual nslookup using them (or any other DNS server) failed to resolve any addresses. My understanding is that this is likely some sort of firewall issue, but other containers are able to send outbound requests on UDP 53 with no issues and are otherwise functioning normally wrt internet access. I don't have an advanced firewall (just a consumer router + firewall) and whitelisted UDP 53 on Windows firewall, but this did not result in any changes.

Platform is Docker Desktop for Windows 10 4.30.0 (149282).

Thank you for your assistance.

**Comment by j4ym0** [comment]
does sound like DNS traffic is being blocked. Do you have a firewall on your antivirus? could that be blocking it?

Try changing the dns with `-e DNS_SERVERS=8.8.8.8,8.8.4.4`

**Comment by RangerLink667** [comment]
Reattempted with antivirus completely disabled but no change.
Same also unfortunately with both adding different DNS servers as an environmental variable and by manually attempting a lookup. ICMP works normally when pointed at a given IP.

> / # nslookup google.com
;; communications error to 8.8.8.8#53: timed out

> / # nslookup google.com 1.1.1.1
;; communications error to 1.1.1.1#53: timed out

>/ # ping 1.1.1.1
PING 1.1.1.1 (1.1.1.1): 56 data bytes
64 bytes from 1.1.1.1: seq=0 ttl=63 time=22.655 ms

It just strikes me as odd that DNS would be getting firewalled specifically for this container but no others.

**Comment by RangerLink667** [comment]
Issue found! It was an instance of PIA running on the host machine capturing DNS requests, despite Docker not being routed via PIA. Sorry for the trouble.
