### ISSUE TITLE
Enabling SSL on WebUI

### ISSUE THREAD

**Issue by cookiem3r** [j4ym0/pia-qbittorrent-docker#24]
I attempted to set up https for the Web UI by following the instructions [here](https://github.com/qbittorrent/qbittorrent/wiki/Linux-WebUI-setting-up-HTTPS-with-self-signed-SSL-certificates).

However, it doesn't seem to work as all the javascript and CSS does not load. I also tried to chmod 755 the 2 keys but did not work as well.

Any ideas?

**Comment by cookiem3r** [comment]
qBittorrent v5.0.0 WebUI (64-bit)
________________________________

**Comment by j4ym0** [comment]
i set up ssl and works fine on both 4.x and 5.x. 
i had to change the ownership of the certificate files `chown qbtUser:qbtUser server.crt` and `chown qbtUser:qbtUser server.key`

are you using a alternative Web UI?

**Comment by j4ym0** [comment]
have you checked if there is anything in the logs in /config/qBittorrent/data/logs/qbittorrent.log

**Comment by cookiem3r** [comment]
Did a quick check. Seems like only a single line. Didn't have much time to do some tests. But the surrounding logs didnt seem relevant.

(C) 2024-10-22T14:39:22 - WebUI: HTTPS setup failed, fallback to HTTP

**Comment by cookiem3r** [comment]
I am still learning linux admin, but which account should be the owner of the SSL file?

**Comment by j4ym0** [comment]
the files need to be owned by qbtUser the user id 700 and group id 700 (unless changed with the [environment-variables](https://github.com/j4ym0/pia-qbittorrent-docker#environment-variables)).

if the SSL files are located on the host machine. on the host use the command `sudo chown 700:700 server.crt` and `sudo chown 700:700 server.key`
if you created the SSL files on the container use `sudo docker exec pia-qbittorrent chown qbtUser:qbtUser server.crt` and `sudo docker exec pia-qbittorrent chown qbtUser:qbtUser server.key`
(dont forget the change the server.crt and server.key to the correct name and locations)

**Comment by cookiem3r** [comment]
Thanks a lot. Got the ssl working on your advise.
