### ISSUE TITLE
How to pull the 5.0.0 version via docker

### ISSUE THREAD

**Issue by lignicolos** [j4ym0/pia-qbittorrent-docker#25]
Hello, using docker compose to pull  image: j4ym0/pia-qbittorrent and it's pulling 4.6.7. I tried using the "latest" tag but didn't get qbt 5. Is there a tag I should use to pull the version 5 of qbt? Thanks!

**Comment by j4ym0** [comment]
looks like i have updated the latest feed with an update to the qbittorrent v4.6.7. 
You could use the 5.x-alpine or wait until later tonight when i can update the latest tag with the 5.0.0

**Comment by lignicolos** [comment]
understood! Thank you! just wanted to make sure I didn't have something configured wrong.

**Comment by j4ym0** [comment]
pushed
