### ISSUE TITLE
Stuck on Waiting for VPN to Connect

### ISSUE THREAD

**Issue by bradarussell** [j4ym0/pia-qbittorrent-docker#27]
Hey, thanks for your work on this project!  It's exactly what I'm looking for.  My docker skills are newly acquired, so I may be doing something simple incorrectly.  

I've been running it like this (user and pwd redacted):
`docker run -d --init --name=pia --restart unless-stopped --cap-add=NET_ADMIN \
-v /mnt/torrents/:/downloads -v /qBittorrent/config/:/config \
-p 8888:8888/tcp -e REGION="ca_ontario" -e USER=pusername -e PASSWORD=password \
-e UID=0 -e GID=2222 -e PORT_FORWARDING=true \
j4ym0/pia-qbittorrent`

I've also tried `-p 8888:8888` without tcp.  I thought about trying it with `--network=host` but wasn't sure if that would open something up I didn't want.

It's detecting the local gateway and subnet to be in the 172.17.0.0/16 range, and I'm not sure if that's correct for being in a container or if one/both should be my actual LAN subnet of 192.168.137.x range.

Here's the docker logs I get, but it never moves past this and I'm not sure where to check the attempts to connect to PIA:

`=========================================
 ============== qBittorrent ==============
 =================== + ===================
 ============= PIA CONTAINER =============
 =========================================
 OS: Alpine Linux v3.20
 =========================================
 OpenVPN version: 2.6.11
 Iptables version: v1.8.10
 qBittorrent version: v5.0.0
 =========================================

System parameters:
 * userID: 0
 * groupID: 2222
 * timezone: UTC +0000
OpenVPN parameters:
 * Region: ca_ontario
Local network parameters:
 * Web UI port: 8888
 * Adding PIA DNS Servers
 * * Adding 84.200.69.80 to resolv.conf
 * * Adding 84.200.70.40 to resolv.conf
[INFO] Writing USER and PASSWORD to protected file /auth.conf...DONE
[INFO] Clearing environment variables USER and PASSWORD...DONE
[WARNING] TUN device is not available, creating it...DONE
[INFO] Reading OpenVPN configuration...
 * Port: 1198
 * Domain: ca-ontario.privacy.network
[INFO] Detecting IP addresses corresponding to ca-ontario.privacy.network...
   149.50.218.144
   149.50.218.32
   149.50.218.71
[INFO] Creating target OpenVPN files in /openvpn/target...DONE
[INFO] Finding network properties...
 * Detecting default gateway...172.17.0.1
 * Detecting local interface...eth0
 * Detecting local subnet...172.17.0.0/16
 * Detecting target VPN interface...tun0
[INFO] Checking firewall
 * Current mode: Normal (nftables)
 * iptables set to prefered
[INFO] Setting firewall
 * Blocking everything
   * Deleting all iptables rules...DONE
   * Block input traffic...DONE
   * Block output traffic...DONE
   * Block forward traffic...DONE
 * Creating general rules
   * Accept established and related input and output traffic...DONE
   * Accept local loopback input and output traffic...DONE
   * Accept traffic to webui-port:8888...DONE
 * Creating VPN rules
   * Accept output traffic to VPN server 149.50.218.144 through eth0, port udp 1198...DONE
   * Accept output traffic to VPN server 149.50.218.32 through eth0, port udp 1198...DONE
   * Accept output traffic to VPN server 149.50.218.71 through eth0, port udp 1198...DONE
   * Accept all output traffic through tun0...DONE
 * Creating local subnet rules
   * Accept input and output traffic to and from 172.17.0.0/16...DONE
[INFO] Launching OpenVPN
[INFO] Checking qBittorrent config
[INFO] Waiting for VPN to connect`

I'm also unable to access qbittorrent on the LAN from `http://192.168.137.217:8888' but maybe that's because it has the wrong local subnet that it's allowing traffic from.  My firewall is a Firewalla and it's not showing any blocked flows for the container.  

This is unrelated, but you may want to add something to your documentation for the server lists.  When I tried ones with a space in the name it wouldn't work.  For CA Ontario I tried "CA Ontario" and "ca-ontario", which didn't work.  But "ca_ontario" does.  Maybe something to clarify how to set the region for the ones with spaces would help people.

You certainly don't owe me any help, but if you have any suggestions I'd really appreciate it.  Thanks again for your work on this.

**Comment by j4ym0** [comment]
hi, i will try and help where i can. your docker command looks fine.

The ip range 172.17.0.0/16 is normal and is the internal docker network.

the `-p 8888:8888/tcp` is correct with and without as it is assumed TCP in docker

unfortunately you wont be able to get the the WebUI until the VPN has connected, further configuration has taken place and then qBittorrent is launched. 

i have run into this issue a few time recently, especially on synology NAS. it may be that the tunnel device driver used by openvpn in the container is not available on the host. 
can i know a little more about your host (the OS running docker)?

**Comment by bradarussell** [comment]
This may be a very simple and dumb issue. I tried following the prerequisites, but does openvpn need to be installed separately in the LXC? Any specific version if so? I'll have to check but I doubt I did that.

**Comment by Warlour** [comment]
I had the same issue, and sometimes it comes back. Running the following script to load the tun device works. You should probably run it as root.

```sh
#!/bin/sh

# Create the necessary file structure for /dev/net/tun
if ( [ ! -c /dev/net/tun ] ); then
  if ( [ ! -d /dev/net ] ); then
    mkdir -m 755 /dev/net
  fi
  mknod /dev/net/tun c 10 200
  chmod 0755 /dev/net/tun
fi

# Load the tun module if not already loaded
if ( !(lsmod | grep -q "^tun\s") ); then
  insmod /lib/modules/tun.ko
fi
```
[source](https://www.synoforum.com/threads/device-dev-net-tun-not-working-anymore-after-docker-update-18-09-0-0513.3074/post-14157)

**Comment by bradarussell** [comment]
Thanks for the replies.  I was able to make pretty good progress.  I started a new container with Alpine and Docker and setting up the docker container for this project worked well.  VPN connects and all that is well.

I am now getting a failure in qbittorrent with uPnP.  The result is no seeding is occuring, or very limited at best.  Here's the relevant qbittorrent logs:

`(I) 2024-10-31T03:33:20 - IP geolocation database loaded. Type: DBIP-Country-Lite. Build time: Tue Oct 1 00:47:11 2024.
(N) 2024-10-31T03:33:20 - Using built-in WebUI.
(N) 2024-10-31T03:33:20 - WebUI translation for selected locale (en) has been successfully loaded.
(N) 2024-10-31T03:33:20 - WebUI: Now listening on IP: *, port: 8888
(I) 2024-10-31T03:33:20 - Detected external IP. IP: "149.50.218.219"
(W) 2024-10-31T03:35:56 - UPnP/NAT-PMP port mapping failed. Message: "could not map port using UPnP[10.9.112.140]: no router found"
(W) 2024-10-31T03:35:56 - UPnP/NAT-PMP port mapping failed. Message: "could not map port using UPnP[10.9.112.140]: no router found"
(W) 2024-10-31T03:35:56 - UPnP/NAT-PMP port mapping failed. Message: "could not map port using UPnP[10.9.112.140]: no router found"
(N) 2024-10-31T03:38:16 - Trying to listen on the following list of IP addresses: "tun0:57688"`

It looks like it's trying to use uPnP on the PIA gateway.  Here's the logs from the docker container:

 `=========================================
 ============== qBittorrent ==============
 =================== + ===================
 ============= PIA CONTAINER =============
 =========================================
 OS: Alpine Linux v3.20
 =========================================
 OpenVPN version: 2.6.11
 Iptables version: v1.8.10
 qBittorrent version: v5.0.0
 =========================================

System parameters:
 * userID: 0
 * groupID: 2222
 * timezone: UTC +0000
OpenVPN parameters:
 * Region: ca_ontario
Local network parameters:
 * Web UI port: 8888
 * Adding PIA DNS Servers
 * * Adding 84.200.69.80 to resolv.conf
 * * Adding 84.200.70.40 to resolv.conf
[INFO] Writing USER and PASSWORD to protected file /auth.conf...DONE
[INFO] Clearing environment variables USER and PASSWORD...DONE
[WARNING] TUN device is not available, creating it...DONE
[INFO] Reading OpenVPN configuration...
 * Port: 1198
 * Domain: ca-ontario.privacy.network
[INFO] Detecting IP addresses corresponding to ca-ontario.privacy.network...
   149.50.218.219
   149.50.218.76
   149.50.218.64
[INFO] Creating target OpenVPN files in /openvpn/target...DONE
[INFO] Finding network properties...
 * Detecting default gateway...172.17.0.1
 * Detecting local interface...eth0
 * Detecting local subnet...172.17.0.0/16
 * Detecting target VPN interface...tun0
[INFO] Checking firewall
 * Current mode: Normal (nftables)
 * iptables set to prefered
[INFO] Setting firewall
 * Blocking everything
   * Deleting all iptables rules...DONE
   * Block input traffic...DONE
   * Block output traffic...DONE
   * Block forward traffic...DONE
 * Creating general rules
   * Accept established and related input and output traffic...DONE
   * Accept local loopback input and output traffic...DONE
   * Accept traffic to webui-port:8888...DONE
 * Creating VPN rules
   * Accept output traffic to VPN server 149.50.218.219 through eth0, port udp 1198...DONE
   * Accept output traffic to VPN server 149.50.218.76 through eth0, port udp 1198...DONE
   * Accept output traffic to VPN server 149.50.218.64 through eth0, port udp 1198...DONE
   * Accept all output traffic through tun0...DONE
 * Creating local subnet rules
   * Accept input and output traffic to and from 172.17.0.0/16...DONE
[INFO] Launching OpenVPN
[INFO] Checking qBittorrent config
[INFO] Waiting for VPN to connect
[INFO] Setting up port forwarding
 * Got PIA token
 * Got PIA gateway 10.9.112.1
 * Getting PIA Signature
 * Got signature
 * Decoded payload
 * Your Forwarding port is 57688
 * port scheduled for add
 * adding port to firewall
[INFO] Launching qBittorrent
WebUI will be started shortly after internal preparations. Please wait...

******** Information ********
To control qBittorrent, access the WebUI at: http://localhost:8888`

And here's my qBittorrent advanced config:

![image](https://github.com/user-attachments/assets/a1c1e5ff-82fa-4df0-ae3f-8e106fcdd2cb)

![image](https://github.com/user-attachments/assets/8fb764b2-c490-4720-b575-2793ac57acb2)

Any idea how to get the router port forwarding to work properly?

Unrelated, but when a region is not set, does it do an auto search for the one with the lowest latency?  Or how does it pick one?

**Comment by j4ym0** [comment]
check to connection tab that port 57688 is configured. the entry on qbittorrent log says `Trying to listen on the following list of IP addresses: "tun0:57688"` which is looks to be working correct. 

qbittorrent will try and open the port on the router but the router is a virtual network so fails, then it defaults to the tun device (VPN).

seeding depends on may factors, try a torrent with a different tracker. if you can get maintained connections then should be working fine. 

if not region is set it will not connect to any servers, i should set a default.

**Comment by bradarussell** [comment]
I was able to get the container working.  I created a new Alpine LXC with docker and that worked.  So I must've had something wrong on my end originally.  Thanks a lot!

I have not been able to get uPnP working.  Should it work with the docker container in an LXC, on a server, connected to a router?  Or is that outside the scope of what you're trying to do?

**Comment by bradarussell** [comment]
Ok, I actually may have found something.  In the `docker logs pia` I get the following:

`[INFO] Setting up port forwarding
 * Got PIA token
 * Got PIA gateway 10.8.112.1
 * Got PIA token
 * Got signature
 * Decoded payload
 * Your Forwarding port is 37468
 * port scheduled for add
 * adding port to firewall
[INFO] Launching qBittorrent
WebUI will be started shortly after internal preparations. Please wait...`

However...when I run `tcpdump -i docker0` the only ports I get are 1198 and 36596.  I tried stopping the container and starting a few times to get new ports, but each time they differ.  If I change the qbittorrent connection port manually to the port traffic is coming in on, I get a red connection status, but I'm still seeding some.  Is there an issue in getting the port from the payload with PIA?  Or am I missing something else?

**Comment by j4ym0** [comment]
@bradarussell The ports you mentioned are for openvpn connection, OpenVPN usually has a incoming and outgoing port. All traffic from the container is sent though the VPN to prevent any leak to your ISP.

The forwarding port is leased to you per connection, if the container is restarted a new port will be assigned. If your internet connection drops the port will try to be reassigned but cannot be guaranteed. The port is opened on the IP address at PIA through the VPN, not locally.

**Comment by bjoernh** [comment]
I had the same issue after upgrading to latest docker image. Several attempts with latest docker image always stuck on `Waiting for VPN to Connect`. First attempt with the previous version (includes qBittorrent v4.6.6 for reference) is working without issues.

**Comment by j4ym0** [comment]
> I had the same issue, and sometimes it comes back. Running the following script to load the tun device works. You should probably run it as root.
> 
> ```sh
> #!/bin/sh
> 
> # Create the necessary file structure for /dev/net/tun
> if ( [ ! -c /dev/net/tun ] ); then
>   if ( [ ! -d /dev/net ] ); then
>     mkdir -m 755 /dev/net
>   fi
>   mknod /dev/net/tun c 10 200
>   chmod 0755 /dev/net/tun
> fi
> 
> # Load the tun module if not already loaded
> if ( !(lsmod | grep -q "^tun\s") ); then
>   insmod /lib/modules/tun.ko
> fi
> ```
> [source](https://www.synoforum.com/threads/device-dev-net-tun-not-working-anymore-after-docker-update-18-09-0-0513.3074/post-14157)

Have you tried the above script on the host to enable the tunnel drivers if they are not enabled on the kernel 

Also

Try adding `-e LEGACY_IPTABLES=true` [from issue 16](https://github.com/j4ym0/pia-qbittorrent-docker/issues/16)

**Comment by grivanov** [comment]
I'm having the same issue. Cannot be resolved with the mentioned methods here.

**Comment by j4ym0** [comment]
@grivanov can you run this command `sudo docker exec pia-qbittorrent openvpn --config /openvpn/targe                                                                                                             t/config.ovpn` from ssh while the container is running. change pia-qbittorrent to your container name if needed

**Comment by grivanov** [comment]
Yup. Here is the result:

2024-12-01 00:49:05 DEPRECATED OPTION: --cipher set to 'aes-128-cbc' but missing in --data-ciphers (AES-256-GCM:AES-128-GCM:CHACHA20-POLY1305). OpenVPN ignores --cipher for cipher negotiations. 
2024-12-01 00:49:05 OpenVPN 2.6.11 aarch64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD]
2024-12-01 00:49:05 library versions: OpenSSL 3.3.2 3 Sep 2024, LZO 2.10
2024-12-01 00:49:05 TCP/UDP: Preserving recently used remote address: [AF_INET]37.46.115.17:1198
2024-12-01 00:49:05 UDPv4 link local: (not bound)
2024-12-01 00:49:05 UDPv4 link remote: [AF_INET]37.46.115.17:1198
2024-12-01 00:49:05 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
2024-12-01 00:49:07 [belgrade402] Peer Connection Initiated with [AF_INET]37.46.115.17:1198
2024-12-01 00:49:07 sitnl_send: rtnl: generic error (-101): Network unreachable
2024-12-01 00:49:07 ERROR: Cannot open TUN/TAP dev /dev/net/tun: Operation not permitted (errno=1)
2024-12-01 00:49:07 Exiting due to fatal error

**Comment by j4ym0** [comment]
you have tried this? on the host os?

> I had the same issue, and sometimes it comes back. Running the following script to load the tun device works. You should probably run it as root.
> 
> ```shell
> #!/bin/sh
> 
> # Create the necessary file structure for /dev/net/tun
> if ( [ ! -c /dev/net/tun ] ); then
>   if ( [ ! -d /dev/net ] ); then
>     mkdir -m 755 /dev/net
>   fi
>   mknod /dev/net/tun c 10 200
>   chmod 0755 /dev/net/tun
> fi
> 
> # Load the tun module if not already loaded
> if ( !(lsmod | grep -q "^tun\s") ); then
>   insmod /lib/modules/tun.ko
> fi
> ```
> 
> [source](https://www.synoforum.com/threads/device-dev-net-tun-not-working-anymore-after-docker-update-18-09-0-0513.3074/post-14157)

what is the host OS?
are you running it on a server, NAS, docker for windows, etc?

**Comment by grivanov** [comment]
Okay, so reading the output, decided to now add thus to my compose file, and it works now: 

```
devices:
  - /dev/net/tun:/dev/net/tun
```
 
However, I don't have an explanation why this happened. All I did was update the container, did not change anything at all. It was just a simple re-pull and re-deploy. I'm using the Docker tag "latest-alpine". I'm running on RaspberryPi 5 - `Linux raspberrypi 6.6.62+rpt-rpi-2712 #1 SMP PREEMPT Debian 1:6.6.62-1+rpt1 (2024-11-25) aarch64 GNU/Linux`. 

Is it safe or considered okay to pass the /dev/net/tun device in such a manner?

**Comment by grivanov** [comment]
> you have tried this? on the host os?
> 
> > I had the same issue, and sometimes it comes back. Running the following script to load the tun device works. You should probably run it as root.
> > ```shell
> > #!/bin/sh
> > 
> > # Create the necessary file structure for /dev/net/tun
> > if ( [ ! -c /dev/net/tun ] ); then
> >   if ( [ ! -d /dev/net ] ); then
> >     mkdir -m 755 /dev/net
> >   fi
> >   mknod /dev/net/tun c 10 200
> >   chmod 0755 /dev/net/tun
> > fi
> > 
> > # Load the tun module if not already loaded
> > if ( !(lsmod | grep -q "^tun\s") ); then
> >   insmod /lib/modules/tun.ko
> > fi
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > [source](https://www.synoforum.com/threads/device-dev-net-tun-not-working-anymore-after-docker-update-18-09-0-0513.3074/post-14157)
> 
> what is the host OS? are you running it on a server, NAS, docker for windows, etc?

Just to clarify, yes, I tried it but did not help. However, as I wrote above - passing the **/dev/net/tun** to the container solved the issue. I'm not sure, however, is this a good idea, I'm not that experienced.

**Comment by j4ym0** [comment]
did you have have cap NET_ADMIN? 

The issue seams to be the container does not have access to the tun device or module required for openvpn. NET_ADMIN is required to create the tunnel on most VPN's.

adding --device=/dev/net/tun should be safe as it will only grants the container access to the specific tun device for the VPN.

**Comment by grivanov** [comment]
Yes, I already had and still have ` cap_add:       - NET_ADMIN` in my compose file.

**Comment by j4ym0** [comment]
Ok, strange as that usually allows access for the vpn to create a tunnel. will have to look into Debian and maybe try and add something into the logging when starting up.
Thanks!

**Comment by grivanov** [comment]
And thank you very much, @j4ym0 , for the whole Docker image and the help with this issue here. Running `sudo docker exec pia-qbittorrent openvpn --config /openvpn/target/config.ovpn` and seeing the output really helped me get an idea. :)

**Comment by Kickbut101** [comment]
I have done pretty much what OP did here and now have same issue. My container was up and running for multiple weeks and only recently did I restart it and now without having changed anything it is stuck on "Waiting for VPN to connect".
I'm not certain this is closed/resolved.

I will try the dev/net/tun passthrough

**Comment by tusx** [comment]
@j4ym0 i want to add something, i ran the script mentioned in the wiki for this issue and rerun the container and it didn't work.
Then i add the 
`--device=/dev/net/tun`
Which did work and was able to have the container running as expected.
But i found that with this done i was not able to access Portainer, for some reason im not sure what it interferes with Portainer.
After stooping the PIA+Qbit Container i was easily able to access the Portainer WebUI.

Do you know what might be the issue here?

**Comment by grivanov** [comment]
@tusx , just would like to mention that I'm also using Portainer to manage my containers and don't have an issue with `--device=/dev/net/tun`. Do you know if you accidentally set duplicate ports or something?

**Comment by tusx** [comment]
@grivanov with you mentioning that you don't have any issues it seems like i found what was wrong.
i was adding the `--device=/dev/net/tun` in portainer itself and not through the docker CLI
![Screenshot 2024-12-16 at 13-36-45 Portainer local](https://github.com/user-attachments/assets/0aaba2ef-91f0-43fc-a427-d146d418508f)

adding the `--device=/dev/net/tun`  through docker CLI seems to have fixed it.
It is weird but thanks for your help @grivanov
