### ISSUE TITLE
Pause/Stop API is broken

### ISSUE THREAD

**Issue by andre-paulo98** [j4ym0/pia-qbittorrent-docker#34]
Hello! I'm using qBittorrent v5.0.2 WebUI (64-bit) (with your modifications) and after updating to 5.0.2 the API method `/torrents/pause` changed to `/torrents/stop`.
However I can't seem able to do it, I always get "Bad Request"
From qbit side seems like the API was a simple renaming, and some API clients simply renamed the method.
For reference: https://github.com/qbittorrent/qBittorrent/issues/21561 

Any idea why this could be happening?

**Comment by j4ym0** [comment]
@andre-paulo98 I do not modify qbittorrent. The container and it's scripts are designed to isolate qbittorrent for your internet and direct all connections through PIA and prevent leaking of you Identity.

Are you using an alternative webui?

Are you able to interact with other parts of the API without issues?

**Comment by andre-paulo98** [comment]
> Are you using an alternative webui?

No, from what I gathered from the linked issue, the problems with a custom WebUI is that the Custom WebUI is using the old endpoints, which isn't the case

> Are you able to interact with other parts of the API without issues?

Yes. At least login and listing torrents is working fine.
Cant run `/api/v2/torrents/stop` or `/api/v2/torrents/start`

**Comment by j4ym0** [comment]
Are you using a POST request as per the [documentation](https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)#general-information) as the server will return 405 Method Not Allowed when you used the wrong request method`

i tested a POST request here and worked, but a GET request got Method Not Allowed.

**Comment by andre-paulo98** [comment]
> Are you using a POST request as per the [documentation](https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)#general-information) as the server will return 405 Method Not Allowed when you used the wrong request method`
> 
> i tested a POST request here and worked, but a GET request got Method Not Allowed.

![image](https://github.com/user-attachments/assets/5d381729-0fd7-4964-9267-fabd68ca021f)

This is the cURL request: `curl  --location --request POST 'https://qbit.example.com/api/v2/torrents/start?hashes=06878....' --header 'Cookie: SID=mycookie'`, also tried replacing the domain (which is behind nginx) with the direct IP and port and got the same result.

I'm properly authentication (otherwise I would get a 403 Forbidden) and when I try with GET I also get Method Not Allowed.

**Comment by andre-paulo98** [comment]
![image](https://github.com/user-attachments/assets/ad978e8a-3c34-48dc-b69c-13b9706fab67)

**Comment by j4ym0** [comment]
looking at the curl request again you are performing a post request without any data using the GET uri. 
should be `curl --request POST -d 'hashes=1c482....' --cookie "SID=auth_cookie" https://qbit.server.com/api/v2/torrents/start`

**Comment by j4ym0** [comment]
checked again behind a proxy and `curl -X POST --cookie "SID=$SID" https://$SERVER/api/v2/torrents/start?hashes=$HASHES` gives `Bad Request` this is because there is no data posted to the api. it is essentially posting nothing to the get url.

The request should be `curl -X POST -d "hashes=$HASHES" --cookie "SID=$SID" https://$SERVER/api/v2/torrents/stop` and `curl -X POST -d "hashes=$HASHES" --cookie "SID=$SID" https://$SERVER/api/v2/torrents/start` the api does not return anything in the body but returns a http code of 200 (adding -i to curl will print the headers)

RE:
> ![image](https://private-user-images.githubusercontent.com/19685105/393517040-5d381729-0fd7-4964-9267-fabd68ca021f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2MTY4MjgsIm5iZiI6MTczMzYxNjUyOCwicGF0aCI6Ii8xOTY4NTEwNS8zOTM1MTcwNDAtNWQzODE3MjktMGZkNy00OTY0LTkyNjctZmFiZDY4Y2EwMjFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA4VDAwMDg0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2NjEwNGVjOWI1ZWE5Nzc3NzA1ZTJiMTU2MGNhOGQ2N2RjYmRmMGU5MzFmMWM3YTcxNWQyOGUwYzM2MDcyYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.l56psP2rv-u4bs6syng1GMSW22BnGowh7NFcuoAO0HI)

Add your hashes key and value to the body tab and that should get it working.

**Comment by andre-paulo98** [comment]
You are right!
I'm not exactly sure where I got the idea that the parameters would go in the URL.
Can confirm that it works just fine.

Thanks for the help and for keeping up with the project!
